/**
 * Generated by scripts/generate-tui-branding-art.mjs — do not edit by hand.
 * Font: Slant (figlet, "DSH OC")
 */

export const BRANDING_FONT = "Slant"

/** "DSH" rendered in figlet Slant. */
export const DSH = [
  "    ____  _____ __  __",
  "   / __ \\/ ___// / / /",
  "  / / / /\\__ \\/ /_/ / ",
  " / /_/ /___/ / __  /  ",
  "/_____//____/_/ /_/   "
]

/** "OC" rendered in figlet Slant. */
export const OC = [
  "   ____  ______",
  "  / __ \\/ ____/",
  " / / / / /     ",
  "/ /_/ / /___   ",
  "\\____/\\____/   "
]
