#!/usr/bin/env bash
# List or delete stale .e2e run directories created by the e2e harness.
#
# Usage:
#   bash scripts/cleanup-e2e-runs.sh [--keep N] [--apply]
#
# Default keep is 10 and without --apply this only lists candidates. All
# runs under .e2e are temporary harness outputs (DSH_HOME + mock state);
# they are regenerated by every e2e run and are not tracked by git.
set -euo pipefail
cd "$(dirname "$0")/.."

KEEP=10
APPLY=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --keep) KEEP="${2:-10}"; shift 2 ;;
    --keep=*) KEEP="${1#--keep=}"; shift ;;
    --apply) APPLY=1; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [[ ! -d .e2e ]]; then
  echo "cleanup-e2e-runs: no .e2e directory"
  exit 0
fi

mapfile -t runs < <(
  find .e2e -mindepth 1 -maxdepth 1 -type d -printf '%T@ %p\n' \
    | sort -nr \
    | awk '{ print $2 }'
)
TOTAL="${#runs[@]}"
if [[ "$TOTAL" -le "$KEEP" ]]; then
  echo "cleanup-e2e-runs: $TOTAL runs, none older than keep=$KEEP"
  exit 0
fi

STALE=("${runs[@]:KEEP}")
echo "cleanup-e2e-runs: $TOTAL runs total, removing ${#STALE[@]} older than keep=$KEEP"
printf '  %s\n' "${STALE[@]:0:10}"
if [[ "${#STALE[@]}" -gt 10 ]]; then
  echo "  ... and $(( ${#STALE[@]} - 10 )) more"
fi

if [[ "$APPLY" != "1" ]]; then
  echo "dry-run: pass --apply to delete them"
  exit 0
fi

for run in "${STALE[@]}"; do
  rm -rf -- "$run"
done
echo "removed ${#STALE[@]} runs"
